### ISSUE TITLE
ChatGPT never displays a result.

### ISSUE THREAD

**Issue by simonron** [chathub-dev/chathub#1101] opened 2024-03-02 17:04 UTC
The progress gif is displayed and nothing else ever happens. However, when visiting ChatGPT outside of Chathub the question is there and has been answered  fully.
Further, only 3.5 is used. I presumed cahtGPT4 would have been used. That is why I paid for Premium. If this is not the case, I want my money back please as chathub is no better than just opening several browsers.

**Comment by vincenzomanzoni** [comment] 2024-03-03 14:47
I'm experiencing the same issue: requests to ChatGPT-3.5, whether in comparison to other models or to itself, remain stuck. If I enter the chat interface on chat.openai.com directly, I can see the requests and responses in the history sidebar.

**Comment by wong2** [comment] 2024-03-03 14:53
What browsers are you using?

**Comment by simonron** [comment] 2024-03-03 15:00
Chome on a Macbook pro M1

**Comment by wong2** [comment] 2024-03-03 15:10
Unfortunately I can't reproduce this issue, but I will keep trying

**Comment by vincenzomanzoni** [comment] 2024-03-03 15:23
Microsoft Edge

**Comment by digitalmantra** [comment] 2024-03-03 16:44
I get the same issue. ChatGPT never completes a request with the three dots or eclipses never changing its "i'm working" status.

**Comment by pcarras** [comment] 2024-03-03 20:08
Same problem here. Chrome on OSX.

**Comment by wong2** [comment] 2024-03-04 04:19
I've figured out the reason for this issue: OpenAI is testing the request response based on the websocket protocol in the gray scale. I have made it compatible in the next version under ChatHub, and now it's waiting for Chrome store's review.

**Comment by allentown521** [comment] 2024-03-04 05:23
me too

**Comment by wong2** [comment] 2024-03-04 06:12
Fixed in v2.11.3, please upgrade: https://doc.chathub.gg/miscellaneous/update-manually

**Comment by simonron** [comment] 2024-03-04 07:16
After the upgrade, I have a different error.

{"error":{"message":"You exceeded your current quota, please check your plan and billing details. For more information on this error, read the docs: https://platform.openai.com/docs/guides/error-codes/api-errors.","type":"insufficient_quota","param":null,"code":"insufficient_quota"}}

I have not used any AI sufficiently to go over any current quota. I did not thing  chatGPT3Turbo had a quota anyway.

**Comment by wong2** [comment] 2024-03-04 07:22
@simonron This is not related to the original issue. The error means you're using OpenAI API key, but does not have a credit card connected.

**Comment by wong2** [comment] 2024-03-04 07:23
@simonron If you're not intended to use OpenAI API to access GPT models, you should use "ChatGPT" bot in ChatHub, instead of the "OpenAI" bot.

**Closed** 2024-03-04 07:24 UTC
Labels: resolved

**Comment by simonron** [comment] 2024-03-04 07:26
That is not the case. A stand alone browser does work correctly. Only the chathab window fails.

**Comment by wong2** [comment] 2024-03-04 07:29
@simonron ChatGPT and OpenAI are two different bots, the first one uses the same API as "chat.openai.com" in your browser, the second uses the official OpenAI API, which requires a credit card.

<img width="516" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/42bce7da-fde0-449b-91a0-c176f2877f17">

**Comment by wong2** [comment] 2024-03-04 07:30
If you're still confused, please open a new issue and I will explain it further, lets not mix different issues here.

**Comment by simonron** [comment] 2024-03-04 07:31
I am using 'Use your own account'.
My API key for gpt 4 has indeed expired - but I am not using it.

**Comment by wong2** [comment] 2024-03-04 07:32
@simonron Can you attach a screenshot ChatHub when the error occur? Thanks

**Comment by simonron** [comment] 2024-03-04 07:35
Interestingly, a single window display in chathub now works, but when used with five others - it fails 
![CleanShot 2024-03-04 at 07 33 41@2x](https://github.com/chathub-dev/chathub/assets/1818394/c6520fc4-52fc-4124-8531-3d45a35b0df8)
![CleanShot 2024-03-04 at 07 34 08@2x](https://github.com/chathub-dev/chathub/assets/1818394/6457e15f-950d-4018-94ea-f5dc0f9dace6)

**Comment by wong2** [comment] 2024-03-04 07:36
@simonron You're using "OpenAI" bot here

<img width="330" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/79fbb87e-7ad0-4d33-8e85-1d5de3576493">

**Comment by simonron** [comment] 2024-03-04 07:37
AH! I see it now...
