### ISSUE TITLE
Won't talk to bing/chat

### ISSUE THREAD

**Issue by yookibooki** [chathub-dev/chathub#817] opened 2023-10-03 10:19 UTC
Won't talk to bing/chat, it says:
ServiceClient failure for UserOffense
 ---> Failed to call "UserOffense" at "https://koreasouth.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide". StatusCode=BadRequest - ReasonPhrase=Bad Request. Details: 

I think binginternal.com's service is down.
Chrome version:  117.0.5938.132
OS version: Windows NT 10.0.19045

**Comment by xiyan818** [comment] 2023-10-04 02:46
i have the **same** problem.
ServiceClient failure for UserOffense
 ---> Failed to call "UserOffense" at "https://WestUS2.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide". StatusCode=BadRequest - ReasonPhrase=Bad Request. Details:

**Comment by Mjmaster** [comment] 2023-10-04 09:38
same here:
ServiceClient failure for UserOffense
 ---> Failed to call "UserOffense" at "https://koreasouth.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide". StatusCode=BadRequest - ReasonPhrase=Bad Request. Details: 

Chrome version: 117.0.5938.150
OS version: Windows 11 Pro 21H2 build 22000.2416

**Comment by xjin15** [comment] 2023-10-04 12:30
same here
ServiceClient failure for UserOffense ---> Failed to call "UserOffense" at "https://koreasouth.bing.prod.dlis.binginternal.com/route/wit.InappropriatenessClassifier_V1_0_7_1_Prod_Sydney_BotSide". StatusCode=BadRequest - ReasonPhrase=Bad Request. Details:

Chrome version:117.0.5938.132
OS version: 版本	Windows 11 家庭中文版
版本	22H2
安装日期	‎2023-‎09-‎17
操作系统版本	22621.2283
体验	Windows Feature Experience Pack 1000.22662.1000.0

**Comment by wong2** [comment] 2023-10-05 05:48
Duplicate of #813

**Closed by wong2** 2023-10-05 05:48 UTC
