### ISSUE TITLE
Bing 404 also.

### ISSUE THREAD

**Issue by yuandj** [chathub-dev/chathub#178] opened 2023-03-24 20:18 UTC
hello, Is't bing 

 (404  (https://edgeservices.bing.com/edgesvc/turing/conversation/create))

**Comment by yuandj** [comment] 2023-03-24 20:20
chatGPT ALSO

Failed to fetch

**Comment by 1140209777** [comment] 2023-03-25 01:07
我也遇到了404的问题

**Comment by wong2** [comment] 2023-03-25 03:07
Duplicate of #99

**Closed by wong2** 2023-03-25 03:07 UTC
