### ISSUE TITLE
显示为Failed to fetch (https://www.bing.com/turing/conversation/create)，应该怎么处理？谢谢！

### ISSUE THREAD

**Issue by wu7chao** [chathub-dev/chathub#149] opened 2023-03-23 02:09 UTC
显示为Failed to fetch (https://www.bing.com/turing/conversation/create)， 应该怎么处理？谢谢！

**Comment by wong2** [comment] 2023-03-23 03:17
Duplicate of #99

**Closed by wong2** 2023-03-23 03:17 UTC
