### ISSUE TITLE
Chat GPT 4 connection fails.

### ISSUE THREAD

**Issue by mbhullar** [chathub-dev/chathub#1130] opened 2024-03-22 04:46 UTC
**400 {"detail":"There was a problem with your chat request. Please use a different browser or try again later."} With Chat GPT

OS Name	Microsoft Windows 11 Home
Version	10.0.22631 Build 22631
Version 122.0.6261.113 (Official Build) (64-bit)- Chrome
Settings (v2.18.1)

**Comment by wong2** [comment] 2024-03-22 06:40
Duplicate of #1129

**Closed by wong2** 2024-03-22 06:40 UTC

**Comment by chrahman** [comment] 2024-04-10 18:02
@wong2 Could you please tell me what was the issue & how you fixed it? I have also made a hobby extension & I am also using ```https://chat.openai.com/backend-api/conversation``` API but now my extension is experiencing this response error.

Thanks in advance!

**Comment by sumanth1994** [comment] 2024-04-11 19:22
@chrahman that didnt work for me.

```
const accessToken = await getToken();
console.log("Access Token: ", accessToken);
const arkoseToken = await getArkoseToken();
console.log("Arkose Token: ", arkoseToken);
const res = await fetch(
    "https://chat.openai.com/backend-api/conversation",
    {
        method: "POST",
        headers: {
            "Content-Type": "application/json",
            Authorization: "Bearer " + accessToken,
            "Openai-Sentinel-Arkose-Token": arkoseToken,
            "Openai-Sentinel-Chat-Requirements-Token": arkoseToken,
        },
        body: JSON.stringify({
            action: "next",
            messages: [
                {
                    id: uid(),
                    role: "user",
                    content: {
                        content_type: "text",
                        parts: [question],
                    },
                },
            ],
            model: "text-davinci-002-render-sha",
            parent_message_id: uid(),
        }),
    }
);
resolve(res.body);

**Comment by chrahman** [comment] 2024-04-11 20:37
Ah, Again I have spent some time analyzing the issue, you have to use ```access_token``` in the headers to get the auth arkose token, if you are working with ```https://chat.openai.com/backend-anon/``` then you don't need access_token to get arkose token.

Of course as I mentioned this API is ```https://chat.openai.com/backend-anon/``` for no auth.
And this API requires auth ```https://chat.openai.com/backend-api/```

**Comment by Drjacky** [comment] 2024-06-02 09:48
@chrahman By without login, does it mean then we do not need to [pay](https://openai.com/api/pricing/) anymore?!
