### ISSUE TITLE
bing不能用了

### ISSUE THREAD

**Issue by weizhenhuan** [chathub-dev/chathub#124] opened 2023-03-20 08:52 UTC
<img width="989" alt="image" src="https://user-images.githubusercontent.com/55399998/226290603-dd0d9669-dd4d-44b1-94e4-cebbd10b0328.png">

**Comment by wong2** [comment] 2023-03-20 09:15
Duplicate of #99

**Closed by wong2** 2023-03-20 09:15 UTC

**Comment by ypmjx123** [comment] 2023-03-20 09:23
> <img alt="image" width="989" src="https://user-images.githubusercontent.com/55399998/226290603-dd0d9669-dd4d-44b1-94e4-cebbd10b0328.png">

要新版本的chathub
