### ISSUE TITLE
I got 403 forbidden when using claude.

### ISSUE THREAD

**Issue by ji4** [chathub-dev/chathub#1048] opened 2024-02-02 03:57 UTC
**Describe the bug**
I got 403 forbidden when using claude. I just newly installed ChatHub in my new browser setting. It can work normally in my previous one.
<img width="1185" alt="截圖 2024-02-02 上午11 47 50" src="https://github.com/chathub-dev/chathub/assets/17978366/8e0692fc-af4e-4460-aaeb-e3f7e662b406">

On Claude, it shows that I'm in a normal login status.
<img width="846" alt="截圖 2024-02-02 上午11 48 06" src="https://github.com/chathub-dev/chathub/assets/17978366/b56b77e2-8b1d-47c7-a86e-ffe03e67a652">

**Desktop (please complete the following information):**
 - OS: Mac OS 
 - Browser: Chrome
 - ChatHub Version: v2.4.3

**Comment by wong2** [comment] 2024-02-02 04:00
Can you chat normally on Claude website?

**Comment by ji4** [comment] 2024-02-02 04:55
> Can you chat normally on Claude website?
Yes
![Uploading 截圖 2024-02-02 中午12.55.19.png…]()

**Comment by ji4** [comment] 2024-02-02 05:27
I just happened to encounter an error message that came out on ChatGPT on ChatHub, while it's normal on Claude in my previous Chrome setting. But it then became normally after I sent another message.
<img width="1300" alt="截圖 2024-02-02 下午1 20 27" src="https://github.com/chathub-dev/chathub/assets/17978366/c7c2488d-f6ee-4e44-9db9-a1be8ba1a8e5">

**Comment by wong2** [comment] 2024-02-02 07:10
Usually this is some network issue

**Comment by ji4** [comment] 2024-02-02 08:00
> Usually this is some network issue

It's weird. I got 403 forbidden on Claude on ChatHub in my new Chrome profile all the time.

**Comment by wong2** [comment] 2024-02-02 11:27
@ji4 I see. I think you need to visit claude.ai for the first time, so they can set some cookies for you.

**Comment by ji4** [comment] 2024-02-06 11:57
> Collaborator

Now here it comes out another error message:
<img width="551" alt="截圖 2024-02-06 晚上7 46 38" src="https://github.com/chathub-dev/chathub/assets/17978366/f98695bd-6842-40c2-9d6d-595eb11b5612">

As you mentioned, there is no use to log out Claude and then login to use Claude first.

**Comment by wong2** [comment] 2024-02-06 11:58
@ji4 Thanks, I've identified the cause, and this will be fixed in the next version of ChatHub.

**Comment by wong2** [comment] 2024-02-06 12:58
Can you try the latest version 2.6.0?

**Closed** 2024-02-07 01:10 UTC
