### ISSUE TITLE
fail in side panel in Chrome

### ISSUE THREAD

**Issue by endaye** [chathub-dev/chathub#1021] opened 2024-01-16 09:36 UTC
**Describe the bug**
I am a subscripted member and already activated my extension. 
Nothing shows in the Chrome side panel here.

![image](https://github.com/chathub-dev/chathub/assets/4829591/a207a635-e0aa-492a-bcf2-08b271edf210)

**Desktop (please complete the following information):**
 - OS: `Windows 11`
 - Browser: `chrome`
 - ChatHub Version `v2.0.4`

**Comment by wong2** [comment] 2024-01-16 09:37
Duplicate of https://github.com/chathub-dev/chathub/issues/1017
A fix will be released soon.

**Closed by wong2** 2024-01-16 09:37 UTC
