### ISSUE TITLE
Claude (webapp/Claude-2) displays Unexpected agent error

### ISSUE THREAD

**Issue by Shmily0921** [chathub-dev/chathub#718] opened 2023-08-09 15:58 UTC
**Describe the bug**

**Desktop (please complete the following information):**
 - OS: [e.g. Windows]
 - Browser [e.g. chrome, brave]

**Comment by wong2** [comment] 2023-08-10 02:50
Is it always like this?

**Comment by Shmily0921** [comment] 2023-08-10 02:56
> 总是这样吗？

It appeared yesterday and today, and it's still there

**Comment by wong2** [comment] 2023-08-10 02:57
May I have your input to Claude? I'll try to reproduce it.

**Comment by wong2** [comment] 2023-08-10 04:21
I've found the cause. This issue has been fixed in v1.34.2, please wait for next release.

**Comment by wong2** [comment] 2023-08-10 09:34
The fix has been published to Chrome web store.

**Closed** 2023-08-18 06:57 UTC
