### ISSUE TITLE
Update Bard to Gemini

### ISSUE THREAD

**Issue by Dave-33** [chathub-dev/chathub#1065] opened 2024-02-10 05:58 UTC
update Bard's address from bard.google.com to Gemini at gemini.google.com.

**Comment by kaxzuma** [comment] 2024-02-10 06:04
The following error occurred. I guess the cause this issue.
![image](https://github.com/chathub-dev/chathub/assets/44837694/d75dbfad-d817-4c59-9d84-896bb301742c)

**Comment by wong2** [comment] 2024-02-10 06:05
This has been fixed in v2.6.6
Please upgrade

**Comment by Dave-33** [comment] 2024-02-10 06:13
How can I get update version for Edge? still V 2.3 available in Microsoft Edge Add-On

**Comment by wong2** [comment] 2024-02-10 06:15
Unfortunately, the Edge store review process is much longer than Chrome, it usually takes over 1 week to update. 
So I recommend install from Chrome web store.

**Comment by Dave-33** [comment] 2024-02-10 06:18
Thank you!

**Closed** 2024-02-10 06:25 UTC

**Comment by madnight** [comment] 2024-02-16 22:09
> This has been fixed in v2.6.6 Please upgrade

Where can I find v2.6.6? I can see the version in the chrome store, but I cannot find the tags in this repo and there are no new commits since a month or so: https://github.com/chathub-dev/chathub/tags

**Comment by mwgunt** [comment] 2024-02-19 21:58
@madnight While I am not 100% sure, so please take my comment with a grain of salt, but the developer @wong2 wants to keep the reverse engineering of the Chrome Webstore version private so version 2.x seems to be proprietary while version 1.x is free and open source. My guess is that the main developer wants to monetize ChatHub and making the most recent version of the source code available under a FOSS license would give people a way to get the "Premium" version of the ChatHub extension for free just by downloading the source code from GitHub. Clever, but a dick move in my opinion.
