### ISSUE TITLE
Bard and ChatGPT dont work

### ISSUE THREAD

**Issue by lings22** [chathub-dev/chathub#1059] opened 2024-02-08 23:23 UTC
Bard
┗[GET] "https://bard.google.com/": <no response> Failed to fetch

ChatGPT
┗Our systems have detected unusual activity from your system. Please try again later.

 - OS: Mac
 - Browser: chrome
 - ChatHub Version: v2.6.5

**Comment by wong2** [comment] 2024-02-09 03:49
Duplicate of #1056

**Closed by wong2** 2024-02-09 03:49 UTC
