### ISSUE TITLE
chatGPT对话项目提示Our systems have detected unusual activity from your system

### ISSUE THREAD

**Issue by kura-X** [chathub-dev/chathub#598] opened 2023-06-24 09:09 UTC
**Describe the bug**
之前都正常使用，下午使用chatHub，设置里GPT-4 Mobile或GPT-4 Browsing，发送给chatGPT，都会提示
{"detail":"Our systems have detected unusual activity from your system. Please try again later."}

另行打开chatGPT页面可正常对话

![image](https://github.com/chathub-dev/chathub/assets/11145578/9bc02fc9-f530-4231-9fb3-769c3f0b4170)
![image](https://github.com/chathub-dev/chathub/assets/11145578/d9e8b7aa-6c1e-4e75-8e24-37f9c22f5b87)

**Desktop (please complete the following information):**
 - OS: Windows11，
 - Microsoft Edge版本 114.0.1823.58 (正式版本) (64 位)
 - chatHbub v1.23.5 from edge store

**Comment by kura-X** [comment] 2023-06-24 09:26
补充：模型修改为GPT-3.5无此报错信息

**Comment by wong2** [comment] 2023-06-25 09:33
Duplicate of https://github.com/chathub-dev/chathub/issues/595

**Closed by wong2** 2023-06-25 09:33 UTC
