### ISSUE TITLE
^1

### ISSUE THREAD

**Issue by wilchfort** [chathub-dev/chathub#1044] opened 2024-01-29 15:36 UTC

**Comment by wilchfort** [comment] 2024-01-29 15:39
„broom“ that will clean all open windows at the same time, instead of individually.  Thanks.

**Comment by wong2** [comment] 2024-01-30 03:38
Duplicate of previous issue.

**Closed by wong2** 2024-01-30 03:38 UTC

**Comment by digitalattorney** [comment] 2024-01-30 08:29
> „broom“ that will clean all open windows at the same time, instead of individually. Thanks.

Just click Refresh.

**Comment by wong2** [comment] 2024-01-30 08:32
Many people have requested this, so I've added a button in next version
<img width="915" alt="image" src="https://github.com/chathub-dev/chathub/assets/321947/a524feb7-732b-4a92-9268-b4dcfa2ef602">
